### ISSUE TITLE
Infinite Mesos master log No resources available to allocate! 

### ISSUE THREAD

**Issue by javiroman** [myriad-framework/myriad-vagrant#6]
Problem in resource allocation with Vagrant mesos cluster. We have to tune the cluster.

``
I0218 08:32:57.833915 20228 hierarchical.cpp:1453] No resources available to allocate!
I0218 08:32:57.833950 20228 hierarchical.cpp:1130] Performed allocation for 4 slaves in 212304ns
I0218 08:32:57.833979 20228 clock.cpp:279] Created a timer for (1)@100.0.10.101:5050 in 1secs in the future (2018-02-18 08:32:58.833965056+00:00)
I0218 08:32:58.834239 20230 clock.cpp:152] Handling timers up to 2018-02-18 08:32:58.834220800+00:00
I0218 08:32:58.834282 20230 clock.cpp:159] Have timeout(s) at 2018-02-18 08:32:58.833965056+00:00
I0218 08:32:58.834417 20228 process.cpp:2494] Resuming (1)@100.0.10.101:5050 at 2018-02-18 08:32:58.834407936+00:00
I0218 08:32:58.834610 20228 hierarchical.cpp:1453] No resources available to allocate!
I0218 08:32:58.834633 20228 hierarchical.cpp:1130] Performed allocation for 4 slaves in 179069ns
``

**Comment by javiroman** [comment]
Mesos is working fine:

- At mesos-m1: 
```
[vagrant@mesos-m1 build]$ src/mesos-execute --containerizer=mesos --name=TEST --master=mesos-m1:5050 --command="sleep 60"                                                                     
I0219 06:09:47.457914 26982 sched.cpp:222] Version: 0.28.1
I0219 06:09:47.465348 26996 sched.cpp:326] New master detected at master@100.0.10.101:5050
I0219 06:09:47.465937 26996 sched.cpp:336] No credentials provided. Attempting to register without authentication
I0219 06:09:47.473631 27001 sched.cpp:703] Framework registered with 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0000
Framework registered with 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0000
task TEST submitted to slave a2ef31d5-8984-4989-a63a-3e1d6aecd706-S2
Received status update TASK_RUNNING for task TEST
Received status update TASK_FINISHED for task TEST
I0219 06:10:50.779477 27002 sched.cpp:1903] Asked to stop the driver
I0219 06:10:50.779541 27002 sched.cpp:1143] Stopping framework '7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0000'
```
- The task is scheduled at mesos-a3:

```
I0219 06:09:47.490414 14056 slave.cpp:5367] Launching executor TEST of framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0000 with resources cpus(*):0.1; mem(*):32 in work directory '/var/lib/mesos/slaves/a2ef31d5-8984-4989-a63a-3e1d6aecd706-S2/frameworks/7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0000/executors/TEST/runs/8c56f551-b8bd-4165-bf6b-586188f58612'
I0219 06:09:47.491029 14056 slave.cpp:1698] Queuing task 'TEST' for executor 'TEST' of framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0000
I0219 06:09:47.491359 14056 containerizer.cpp:666] Starting container '8c56f551-b8bd-4165-bf6b-586188f58612' for executor 'TEST' of framework '7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0000'
I0219 06:09:47.497459 14056 linux_launcher.cpp:304] Cloning child process with flags =
I0219 06:09:47.498989 14056 systemd.cpp:95] Assigned child process '18848' to 'mesos_executors.slice'
I0219 06:09:50.677678 14059 slave.cpp:2643] Got registration for executor 'TEST' of framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0000 from executor(1)@100.0.10.104:43914
I0219 06:09:50.679690 14061 slave.cpp:1863] Sending queued task 'TEST' to executor 'TEST' of framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0000 at executor(1)@100.0.10.104:43914
I0219 06:09:50.684078 14059 slave.cpp:3002] Handling status update TASK_RUNNING (UUID: 734c7e6d-4812-431c-b3b8-667d718b4207) for task TEST of framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0000 from executor(1)@100.0.10.104:43914
```

However Myriad framework is declining the offers from Mesos:

```
I0219 06:17:25.756887 26926 hierarchical.cpp:1427] Allocating cpus(*):3; mem(*):2766; disk(*):33229; ports(*):[31000-32000] on slave 6a2d5681-d419-4a8a-ad72-573c576681dd-S0 to framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0001
I0219 06:17:25.757258 26926 hierarchical.cpp:1427] Allocating cpus(*):2; mem(*):919; disk(*):33229; ports(*):[31000-32000] on slave a2ef31d5-8984-4989-a63a-3e1d6aecd706-S0 to framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0001
I0219 06:17:25.757637 26926 hierarchical.cpp:1427] Allocating cpus(*):3; mem(*):2766; disk(*):33229; ports(*):[31000-32000] on slave a2ef31d5-8984-4989-a63a-3e1d6aecd706-S2 to framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0001
I0219 06:17:25.757987 26926 hierarchical.cpp:1427] Allocating cpus(*):3; mem(*):2766; disk(*):33229; ports(*):[31000-32000] on slave a2ef31d5-8984-4989-a63a-3e1d6aecd706-S1 to framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0001
I0219 06:17:25.758296 26924 process.cpp:2494] Resuming master@100.0.10.101:5050 at 2018-02-19 06:17:25.758277888+00:00
I0219 06:17:25.758313 26926 hierarchical.cpp:1548] No inverse offers to send out!
I0219 06:17:25.758347 26926 hierarchical.cpp:1130] Performed allocation for 4 slaves in 1.796617ms
I0219 06:17:25.758378 26926 clock.cpp:279] Created a timer for (1)@100.0.10.101:5050 in 1secs in the future (2018-02-19 06:17:26.758366976+00:00)
I0219 06:17:25.759089 26924 master.cpp:5324] Sending 4 offers to framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0001 (MyriadAlpha) at scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113
I0219 06:17:25.761891 26931 pid.cpp:93] Attempting to parse 'scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113' into a PID
I0219 06:17:25.761919 26931 process.cpp:612] Parsed message name 'mesos.scheduler.Call' for master@100.0.10.101:5050 from scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113
I0219 06:17:25.762066 26931 pid.cpp:93] Attempting to parse 'scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113' into a PID
I0219 06:17:25.762089 26931 process.cpp:612] Parsed message name 'mesos.scheduler.Call' for master@100.0.10.101:5050 from scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113
I0219 06:17:25.762234 26931 pid.cpp:93] Attempting to parse 'scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113' into a PID
I0219 06:17:25.762231 26926 process.cpp:2494] Resuming master@100.0.10.101:5050 at 2018-02-19 06:17:25.762222080+00:00
I0219 06:17:25.762255 26931 process.cpp:612] Parsed message name 'mesos.scheduler.Call' for master@100.0.10.101:5050 from scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113
I0219 06:17:25.762310 26931 pid.cpp:93] Attempting to parse 'scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113' into a PID
I0219 06:17:25.762320 26926 master.cpp:3641] Processing DECLINE call for offers: [ 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-O72 ] for framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0001 (MyriadAlpha) at scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113
I0219 06:17:25.762328 26931 process.cpp:612] Parsed message name 'mesos.scheduler.Call' for master@100.0.10.101:5050 from scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113
I0219 06:17:25.762603 26926 master.cpp:3641] Processing DECLINE call for offers: [ 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-O73 ] for framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0001 (MyriadAlpha) at scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113
I0219 06:17:25.762850 26926 master.cpp:3641] Processing DECLINE call for offers: [ 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-O74 ] for framework 7ef5ad6c-b5e8-4b45-8ee5-304d81ea91ea-0001 (MyriadAlpha) at scheduler-3e13fe4a-fada-47ac-8a74-973edbcbd1a3@100.0.10.101:45113
```

**Comment by javiroman** [comment]
ResourceManager log;
```
2018-02-19 07:30:21,656 ERROR org.apache.myriad.scheduler.event.handlers.ResourceOffersEventHandler: Exception thrown while trying to create a task for nm
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at org.apache.myriad.scheduler.resource.RangeResource.getRandomValues(RangeResource.java:128)
        at org.apache.myriad.scheduler.resource.RangeResource.consumeResource(RangeResource.java:99)
        at org.apache.myriad.scheduler.resource.ResourceOfferContainer.consumePorts(ResourceOfferContainer.java:171)
        at org.apache.myriad.scheduler.NMTaskFactory.createTask(NMTaskFactory.java:45)
        at org.apache.myriad.scheduler.event.handlers.ResourceOffersEventHandler.onEvent(ResourceOffersEventHandler.java:146)
        at org.apache.myriad.scheduler.event.handlers.ResourceOffersEventHandler.onEvent(ResourceOffersEventHandler.java:51)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by javiroman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ResourceOffersEventHandler create a task for nm : bound must be positive](https://trello.com/c/Zm8bXDM3/1-resourceofferseventhandler-create-a-task-for-nm-bound-must-be-positive)

**Comment by javiroman** [comment]
Reported at Incubator JIRA here [1] and here [2].
Fix at https://github.com/DarinJ/incubator-myriad/commit/bdbad388c6da9f2e0e8d6720bd9bba72fb3c651d

[1] https://issues.apache.org/jira/browse/MYRIAD-239
[2] https://issues.apache.org/jira/browse/MYRIAD-248
